name: LMS Docker CI/CD

on:
  push:
    branches: [main]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Containers
        run: docker compose up -d --build

      - name: Wait for Services
        run: sleep 60

      - name: Run Django Migrations
        run: |
          docker exec $(docker ps -qf "name=django") python manage.py migrate

      - name: Run Django Tests
        run: |
          docker exec $(docker ps -qf "name=django") pytest

      - name: Check APIs
        run: |
          curl -f http://localhost:8000/api/schema/ || exit 1
          curl -f http://localhost:8001/docs || exit 1

      - name: Logs on Failure
        if: failure()
        run: docker compose logs

      - name: Stop Containers
        if: always()
        run: docker compose down