name: LMS Docker CI/CD

on:
  push:
    branches: [main]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 🔥 FORCE CLEAN DOCKER STATE
      - name: Clean Docker
        run: |
          docker compose down -v || true
          docker system prune -af || true

      - name: Build & Start Containers
        run: docker compose up -d --build

      - name: Wait for Services
        run: sleep 70

      # 🔥 FIX PERMISSION DIRECTLY (IMPORTANT)
      - name: Fix MySQL Permissions
        run: |
          docker exec $(docker ps -qf "name=db") mysql -uroot -plms_root_password -e "
          GRANT ALL PRIVILEGES ON *.* TO 'lms_user'@'%' WITH GRANT OPTION;
          FLUSH PRIVILEGES;
          "

      - name: Run Migrations
        run: |
          docker exec $(docker ps -qf "name=django") python manage.py migrate

      - name: Run Tests
        run: |
          docker exec $(docker ps -qf "name=django") pytest

      - name: Check APIs
        run: |
          curl -f http://localhost:8000/api/schema/ || exit 1
          curl -f http://localhost:8001/docs || exit 1

      - name: Logs (if failed)
        if: failure()
        run: docker compose logs

      - name: Stop Containers
        if: always()
        run: docker compose down